import { ChecklistItem } from './types';

export const CHECKLIST_DATA: ChecklistItem[] = [
  // 束缚
  { id: 'b1', category: '束缚', label: '肢体束缚 (肢体捆绑)' },
  { id: 'b2', category: '束缚', label: '胸部束缚' },
  { id: 'b3', category: '束缚', label: '私处走绳' },
  { id: 'b4', category: '束缚', label: '眼罩' },
  { id: 'b5', category: '束缚', label: '束缚-轻度' },
  { id: 'b6', category: '束缚', label: '束缚-中度' },
  { id: 'b7', category: '束缚', label: '束缚-重度' },
  { id: 'b8', category: '束缚', label: '笼子/牢房/柜子 (关进去)' },
  { id: 'b9', category: '束缚', label: '锁链' },
  { id: 'b10', category: '束缚', label: '贞操带/贞操锁' },
  { id: 'b11', category: '束缚', label: '项圈-私下佩戴' },
  { id: 'b12', category: '束缚', label: '项圈-公开佩戴' },
  { id: 'b13', category: '束缚', label: '铐-皮革' },
  { id: 'b14', category: '束缚', label: '铐-金属' },
  { id: 'b15', category: '束缚', label: '耳塞/耳罩 (听觉剥夺)' },
  { id: 'b16', category: '束缚', label: '口塞-口球' },
  { id: 'b17', category: '束缚', label: '口塞-口枷/条状/骨头状' },
  { id: 'b18', category: '束缚', label: '口塞-衣物' },
  { id: 'b19', category: '束缚', label: '口塞-充气的' },
  { id: 'b20', category: '束缚', label: '口塞-阳具状' },
  { id: 'b21', category: '束缚', label: '口塞-开口环' },
  { id: 'b22', category: '束缚', label: '口塞-胶带封嘴' },
  { id: 'b23', category: '束缚', label: '鼻勾' },
  { id: 'b24', category: '束缚', label: '挽具/束具-皮革' },
  { id: 'b25', category: '束缚', label: '挽具/束具-绳子' },
  { id: 'b26', category: '束缚', label: '头套 (全包)' },
  { id: 'b27', category: '束缚', label: '限制行动' },
  { id: 'b28', category: '束缚', label: '牵引链' },
  { id: 'b29', category: '束缚', label: '皮革束缚带' },
  { id: 'b30', category: '束缚', label: '镣铐/金属锁链' },
  { id: 'b31', category: '束缚', label: '扎带束缚' },
  { id: 'b32', category: '束缚', label: '木乃伊化 (用静电胶带或绷带缠全身)' },
  { id: 'b33', category: '束缚', label: '嘴套' },
  { id: 'b34', category: '束缚', label: '绳缚-简单' },
  { id: 'b35', category: '束缚', label: '绳缚-复杂 (绳艺)' },
  { id: 'b36', category: '束缚', label: '分腿杆' },
  { id: 'b37', category: '束缚', label: '枷锁 (头和手)' },
  { id: 'b38', category: '束缚', label: '紧身衣' },
  { id: 'b39', category: '束缚', label: '吊缚-正向' },
  { id: 'b40', category: '束缚', label: '吊缚-水平' },
  { id: 'b41', category: '束缚', label: '吊缚-倒置' },
  { id: 'b42', category: '束缚', label: '睡袋' },

  // 体液和功能化
  { id: 'p1', category: '体液和功能化', label: '便壶' },
  { id: 'p2', category: '体液和功能化', label: '中出' },
  { id: 'p3', category: '体液和功能化', label: '射精-在屁股' },
  { id: 'p4', category: '体液和功能化', label: '射精-在口中' },
  { id: 'p5', category: '体液和功能化', label: '射精-在阴道' },
  { id: 'p6', category: '体液和功能化', label: '射精-在身体上' },
  { id: 'p7', category: '体液和功能化', label: '圣水浴' },
  { id: 'p8', category: '体液和功能化', label: '人体厕所' },
  { id: 'p9', category: '体液和功能化', label: '灌肠 (生理盐水)' },
  { id: 'p10', category: '体液和功能化', label: '挤奶 (强制从胸部挤出奶水)' },
  { id: 'p11', category: '体液和功能化', label: '珍珠项链 (在脖子和喉咙处射精)' },
  { id: 'p12', category: '体液和功能化', label: '珍珠浴 (颜射)' },
  { id: 'p13', category: '体液和功能化', label: '舔肛' },
  { id: 'p14', category: '体液和功能化', label: '粪便 (黄金)' },
  { id: 'p15', category: '体液和功能化', label: '吞精' },
  { id: 'p16', category: '体液和功能化', label: '圣水饮' },

  // 恋物癖
  { id: 'f1', category: '恋物癖', label: '鞋靴迷恋' },
  { id: 'f2', category: '恋物癖', label: '女性性器官迷恋' },
  { id: 'f3', category: '恋物癖', label: '阳具迷恋' },
  { id: 'f4', category: '恋物癖', label: '束腰' },
  { id: 'f5', category: '恋物癖', label: '变装 (cd)' },
  { id: 'f6', category: '恋物癖', label: '穿戴尿不湿' },
  { id: 'f7', category: '恋物癖', label: '恋足' },
  { id: 'f8', category: '恋物癖', label: '防毒面具' },
  { id: 'f9', category: '恋物癖', label: '高跟鞋恋物' },
  { id: 'f10', category: '恋物癖', label: '皮革恋物' },
  { id: 'f11', category: '恋物癖', label: '情趣内衣' },
  { id: 'f12', category: '恋物癖', label: '橡胶/乳胶衣恋物' },
  { id: 'f13', category: '恋物癖', label: '丝袜恋物' },
  { id: 'f14', category: '恋物癖', label: '紧身衣 (zentai)' },

  // 羞辱
  { id: 'h1', category: '羞辱', label: '强制穿着' },
  { id: 'h2', category: '羞辱', label: '强制女装' },
  { id: 'h3', category: '羞辱', label: '强制与同性发生性行为' },
  { id: 'h4', category: '羞辱', label: '强制自慰' },
  { id: 'h5', category: '羞辱', label: '强制裸露' },
  { id: 'h6', category: '羞辱', label: '强制服侍' },
  { id: 'h7', category: '羞辱', label: '私下羞辱' },
  { id: 'h8', category: '羞辱', label: '公开羞辱' },
  { id: 'h9', category: '羞辱', label: '对不当行为管教训诫' },
  { id: 'h10', category: '羞辱', label: '剃发' },
  { id: 'h11', category: '羞辱', label: '剃毛 (身体，阴部等)' },
  { id: 'h12', category: '羞辱', label: '站墙角罚站' },
  { id: 'h13', category: '羞辱', label: '言语羞辱' },

  // 打/刑罚play
  { id: 'd1', category: '打/刑罚play', label: '胸部抽打' },
  { id: 'd2', category: '打/刑罚play', label: '鞭打-重' },
  { id: 'd3', category: '打/刑罚play', label: '鞭打-轻' },
  { id: 'd4', category: '打/刑罚play', label: '耳光' },
  { id: 'd5', category: '打/刑罚play', label: '拍打阴部 (拍子)' },
  { id: 'd6', category: '打/刑罚play', label: '抽打阴部 (鞭子/细条)' },
  { id: 'd7', category: '打/刑罚play', label: '马鞭' },
  { id: 'd8', category: '打/刑罚play', label: 'SP-毛刷' },
  { id: 'd9', category: '打/刑罚play', label: 'SP-手掌' },
  { id: 'd10', category: '打/刑罚play', label: 'SP-皮拍' },
  { id: 'd11', category: '打/刑罚play', label: 'SP-木拍' },
  { id: 'd12', category: '打/刑罚play', label: 'SP-橡胶拍' },
  { id: 'd13', category: '打/刑罚play', label: 'SP-亚克力拍' },
  { id: 'd14', category: '打/刑罚play', label: 'SP-以趴在腿上的姿势 (OTK)' },
  { id: 'd15', category: '打/刑罚play', label: '鞭打-皮带' },
  { id: 'd16', category: '打/刑罚play', label: '鞭打-马鞭' },
  { id: 'd17', category: '打/刑罚play', label: '鞭打-藤条' },
  { id: 'd18', category: '打/刑罚play', label: '鞭打-戒尺' },
  { id: 'd19', category: '打/刑罚play', label: '鞭打-散鞭' },
  { id: 'd20', category: '打/刑罚play', label: '鞭打-蛇鞭' },
  { id: 'd21', category: '打/刑罚play', label: '鞭打-热熔胶棒' },

  // 非专一/多人
  { id: 'm1', category: '非专一/多人', label: '轮奸幻想' },
  { id: 'm2', category: '非专一/多人', label: '多人游戏-多男' },
  { id: 'm3', category: '非专一/多人', label: '多人游戏-多女' },
  { id: 'm4', category: '非专一/多人', label: '多人游戏-多男多女' },
  { id: 'm5', category: '非专一/多人', label: '分享 (临时一次性的)' },
  { id: 'm6', category: '非专一/多人', label: '交换 (与另一对伴侣)' },
  { id: 'm7', category: '非专一/多人', label: '交换 (与多对伴侣)' },

  // 角色扮演
  { id: 'r1', category: '角色扮演', label: '抛弃 (幻想)' },
  { id: 'r2', category: '角色扮演', label: '年龄差 (扮演，非恋童癖)' },
  { id: 'r3', category: '角色扮演', label: '照顾与被照顾 (CG/L)' },
  { id: 'r4', category: '角色扮演', label: '宠物扮演' },
  { id: 'r5', category: '角色扮演', label: '恐惧play' },
  { id: 'r6', category: '角色扮演', label: '犬类play' },
  { id: 'r7', category: '角色扮演', label: '婴儿play' },
  { id: 'r8', category: '角色扮演', label: '认主仪式' },
  { id: 'r9', category: '角色扮演', label: '拷问play' },
  { id: 'r10', category: '角色扮演', label: '绑架play' },
  { id: 'r11', category: '角色扮演', label: '医疗场景扮演' },
  { id: 'r12', category: '角色扮演', label: '更改名字' },
  { id: 'r13', category: '角色扮演', label: '骑马play' },
  { id: 'r14', category: '角色扮演', label: '精神病院场景扮演' },
  { id: 'r15', category: '角色扮演', label: '监狱场景扮演' },
  { id: 'r16', category: '角色扮演', label: '办公室场景扮演' },
  { id: 'r17', category: '角色扮演', label: '新婚场景扮演' },
  { id: 'r18', category: '角色扮演', label: '偷情场景扮演' },
  { id: 'r19', category: '角色扮演', label: '妓院场景扮演' },
  { id: 'r20', category: '角色扮演', label: '宗教场景扮演' },
  { id: 'r21', category: '角色扮演', label: '学校教室场景扮演' },
  { id: 'r22', category: '角色扮演', label: 'Switch 角色转换' },
  { id: 'r23', category: '角色扮演', label: '全部权力交换 (total power exchange)' },
  { id: 'r24', category: '角色扮演', label: '其它角色扮演' },

  // 感官刺激 (非打击类)
  { id: 's1', category: '感官刺激 (非打击类)', label: '摩擦 (刮擦，沙磨等)' },
  { id: 's2', category: '感官刺激 (非打击类)', label: '睾丸拉扯' },
  { id: 's3', category: '感官刺激 (非打击类)', label: '咬' },
  { id: 's4', category: '感官刺激 (非打击类)', label: '掐脖子' },
  { id: 's5', category: '感官刺激 (非打击类)', label: '阴蒂/阴唇夹' },
  { id: 's6', category: '感官刺激 (非打击类)', label: '扩张' },
  { id: 's7', category: '感官刺激 (非打击类)', label: '电击-体内 (电击跳蛋或马眼棒' },
  { id: 's8', category: '感官刺激 (非打击类)', label: '电击-体外 (情趣电击器' },
  { id: 's9', category: '感官刺激 (非打击类)', label: '灌肠-以清理为目的' },
  { id: 's10', category: '感官刺激 (非打击类)', label: '灌肠-以调教为目的' },
  { id: 's11', category: '感官刺激 (非打击类)', label: '拔火罐' },
  { id: 's12', category: '感官刺激 (非打击类)', label: '拽头发' },
  { id: 's13', category: '感官刺激 (非打击类)', label: '滴蜡-在身体上' },
  { id: 's14', category: '感官刺激 (非打击类)', label: '滴蜡-在生殖器上' },
  { id: 's15', category: '感官刺激 (非打击类)', label: '滴蜡-低温蜡烛' },
  { id: 's16', category: '感官刺激 (非打击类)', label: '滴蜡-较高温蜡烛' },
  { id: 's17', category: '感官刺激 (非打击类)', label: '冰块' },
  { id: 's18', category: '感官刺激 (非打击类)', label: '踢打' },
  { id: 's19', category: '感官刺激 (非打击类)', label: '针刺滚轮' },
  { id: 's20', category: '感官刺激 (非打击类)', label: '乳夹' },
  { id: 's21', category: '感官刺激 (非打击类)', label: '乳环' },
  { id: 's22', category: '感官刺激 (非打击类)', label: '乳头play-拽/拧/等' },
  { id: 's23', category: '感官刺激 (非打击类)', label: '疼痛-轻度' },
  { id: 's24', category: '感官刺激 (非打击类)', label: '疼痛-重度' },
  { id: 's25', category: '感官刺激 (非打击类)', label: '穿刺 (用针)' },
  { id: 's26', category: '感官刺激 (非打击类)', label: '骑木马' },
  { id: 's27', category: '感官刺激 (非打击类)', label: '用硬物划、刮' },
  { id: 's28', category: '感官刺激 (非打击类)', label: '感官剥夺' },
  { id: 's29', category: '感官刺激 (非打击类)', label: '睡眠剥夺' },
  { id: 's30', category: '感官刺激 (非打击类)', label: '沙袋play (全身打击)' },
  { id: 's31', category: '感官刺激 (非打击类)', label: '真空杯 (真空吸乳真空吸阴玩具' },
  { id: 's32', category: '感官刺激 (非打击类)', label: '轻轻挑逗' },
  { id: 's33', category: '感官刺激 (非打击类)', label: '挠痒痒 (TK)-脚' },
  { id: 's34', category: '感官刺激 (非打击类)', label: '挠痒痒 (TK)-腋下' },
  { id: 's35', category: '感官刺激 (非打击类)', label: '挠痒痒 (TK)-肋侧' },
  { id: 's36', category: '感官刺激 (非打击类)', label: '挠痒痒 (TK)-其它部位' },

  // 服侍, 行为限制/控制
  { id: 'c1', category: '服侍, 行为限制/控制', label: '如厕控制 (许可)' },
  { id: 'c2', category: '服侍, 行为限制/控制', label: '祈求' },
  { id: 'c3', category: '服侍, 行为限制/控制', label: '当司机' },
  { id: 'c4', category: '服侍, 行为限制/控制', label: '家务服侍' },
  { id: 'c5', category: '服侍, 行为限制/控制', label: '指定穿着' },
  { id: 'c6', category: '服侍, 行为限制/控制', label: '指定食物' },
  { id: 'c7', category: '服侍, 行为限制/控制', label: '合同奴隶' },
  { id: 'c8', category: '服侍, 行为限制/控制', label: '每天日记' },
  { id: 'c9', category: '服侍, 行为限制/控制', label: '吃苦锻炼 (例如扎马步俯卧撑等)' },
  { id: 'c10', category: '服侍, 行为限制/控制', label: '艳舞' },
  { id: 'c11', category: '服侍, 行为限制/控制', label: '眼神接触限制' },
  { id: 'c12', category: '服侍, 行为限制/控制', label: '服从命令' },
  { id: 'c13', category: '服侍, 行为限制/控制', label: '姿势训练' },
  { id: 'c14', category: '服侍, 行为限制/控制', label: '多人共同服侍' },
  { id: 'c15', category: '服侍, 行为限制/控制', label: '催眠' },
  { id: 'c16', category: '服侍, 行为限制/控制', label: '跪' },
  { id: 'c17', category: '服侍, 行为限制/控制', label: '冥想' },
  { id: 'c18', category: '服侍, 行为限制/控制', label: '按摩' },
  { id: 'c19', category: '服侍, 行为限制/控制', label: '足部按摩' },
  { id: 'c20', category: '服侍, 行为限制/控制', label: '性格塑造' },
  { id: 'c21', category: '服侍, 行为限制/控制', label: '文爱' },
  { id: 'c22', category: '服侍, 行为限制/控制', label: '语音sex' },
  { id: 'c23', category: '服侍, 行为限制/控制', label: '远程控制电动玩具' },
  { id: 'c24', category: '服侍, 行为限制/控制', label: '礼仪' },
  { id: 'c25', category: '服侍, 行为限制/控制', label: '作为仆人' },
  { id: 'c26', category: '服侍, 行为限制/控制', label: '作为家具' },
  { id: 'c27', category: '服侍, 行为限制/控制', label: '作为艺术品' },
  { id: 'c28', category: '服侍, 行为限制/控制', label: '服侍其他主人 (在监督之下)' },
  { id: 'c29', category: '服侍, 行为限制/控制', label: '语言限制' },
  { id: 'c30', category: '服侍, 行为限制/控制', label: '制服穿着' },
  { id: 'c31', category: '服侍, 行为限制/控制', label: '佩戴标志性饰物' },
  { id: 'c32', category: '服侍, 行为限制/控制', label: '体重控制' },

  // 性行为&入体
  { id: 'x1', category: '性行为&入体', label: '肛门拉珠' },
  { id: 'x2', category: '性行为&入体', label: '肛塞-小' },
  { id: 'x3', category: '性行为&入体', label: '肛塞-中' },
  { id: 'x4', category: '性行为&入体', label: '肛塞-大' },
  { id: 'x5', category: '性行为&入体', label: '肛塞-外出佩戴' },
  { id: 'x6', category: '性行为&入体', label: '肛勾' },
  { id: 'x7', category: '性行为&入体', label: '肛交' },
  { id: 'x8', category: '性行为&入体', label: '乳交' },
  { id: 'x9', category: '性行为&入体', label: '导尿' },
  { id: 'x10', category: '性行为&入体', label: '舔阴 (为女性口交)' },
  { id: 'x11', category: '性行为&入体', label: '被舔/口交' },
  { id: 'x12', category: '性行为&入体', label: '假阳-用于肛门' },
  { id: 'x13', category: '性行为&入体', label: '假阳-用于嘴' },
  { id: 'x14', category: '性行为&入体', label: '假阳-用于阴道' },
  { id: 'x15', category: '性行为&入体', label: '双穴插入' },
  { id: 'x16', category: '性行为&入体', label: '舔阳 (为男性口交)' },
  { id: 'x17', category: '性行为&入体', label: '做爱' },
  { id: 'x18', category: '性行为&入体', label: '自慰' },
  { id: 'x19', category: '性行为&入体', label: '强制自慰' },
  { id: 'x20', category: '性行为&入体', label: '高潮控制' },
  { id: 'x21', category: '性行为&入体', label: '连续高潮' },
  { id: 'x22', category: '性行为&入体', label: '破坏高潮' },
  { id: 'x23', category: '性行为&入体', label: '边缘控制' },
  { id: 'x24', category: '性行为&入体', label: '龟头责' },
  { id: 'x25', category: '性行为&入体', label: '寸止' },
  { id: 'x26', category: '性行为&入体', label: '尿道棒' },
  { id: 'x27', category: '性行为&入体', label: '内窥镜' },
  { id: 'x28', category: '性行为&入体', label: '穿戴式假阳 (口交)' },
  { id: 'x29', category: '性行为&入体', label: '穿戴式假阳 (插入)' },
  { id: 'x30', category: '性行为&入体', label: '穿戴式假阳 (佩戴)' },
  { id: 'x31', category: '性行为&入体', label: '三穴插入' },
  { id: 'x32', category: '性行为&入体', label: '震动玩具-肛门' },
  { id: 'x33', category: '性行为&入体', label: '震动玩具-生殖器外' },
  { id: 'x34', category: '性行为&入体', label: '震动玩具-生殖器内' },

  // 窥视/露出
  { id: 'v1', category: '窥视/露出', label: '身体检查' },
  { id: 'v2', category: '窥视/露出', label: '裸露 (对朋友)' },
  { id: 'v3', category: '窥视/露出', label: '裸露 (对陌生人)' },
  { id: 'v4', category: '窥视/露出', label: '强制裸体 (私下)' },
  { id: 'v5', category: '窥视/露出', label: '强制裸体 (在他人周围)' },
  { id: 'v6', category: '窥视/露出', label: '拍摄色情照片' },
  { id: 'v7', category: '窥视/露出', label: '户外情景' },
  { id: 'v8', category: '窥视/露出', label: '视频 (观看他人)' },
  { id: 'v9', category: '窥视/露出', label: '视频 (录制自己)' },
  { id: 'v10', category: '窥视/露出', label: '窥视 (观看他人)' },
  { id: 'v11', category: '窥视/露出', label: '被窥视 (被主人/其他人看)' },
];

export const INTEREST_LABELS: Record<number, string> = {
  0: '绝对不行 (Hard Limit)',
  1: '没兴趣',
  2: '中立/无感',
  3: '有点好奇',
  4: '很想尝试',
  5: '非常渴望 (Kink)',
};

export const ROLE_LABELS = {
  none: '不适用',
  dom: '作为 主动/S',
  sub: '作为 被动/M',
  switch: '双向/Switch',
};